### PR TITLE
feat: allows the user to specify AWS_SHARED_CREDENTIALS_FILE 

### PR DESCRIPTION
**Pull request by stobias123**
re #12

Really like the git commit hooks btw. :)

### CODE REVIEW

**Review by ryansonshine — CHANGES_REQUESTED** [review]
Just needs some additional test coverage then it'll be good to go

**Comment by ryansonshine** [comment]
@stobias123 I'll pick this up when I have time this week if you don't have time let me know

**Comment by stobias123** [comment]
@ryansonshine  - yeah - tbh this was a pretty quick hack to get this working with a client. Didn't expect such a thorough test suite. 

I likely won't get back to writing tests for a few days

**Comment by ryansonshine** [comment]
@stobias123 No worries; thanks for the PR! I'll update and merge.

**Pull request merged**
